### ISSUE TITLE
Readme Example output is wrong?

### ISSUE THREAD

**Issue by suntong** [santhosh-tekuri/dom#3]
Readme says the Example output is:

```xml
<developer xmlns="www.jroller.com/santhosh/">
    <name>Santhosh Kumar Tekuri</name>
    <email>santhosh.tekuri@gmail.com</email>
</developer>
```

However, when I tried it, I got 

```xml
<developer xmlns="www.jroller.com/santhosh/">
<name>Santhosh Kumar Tekuri</name>
<email>santhosh.tekuri@gmail.com</email>
</developer>
```

I.e., the indent is gone and I see nowhere the indent level can be set.

**Comment by santhosh-tekuri** [comment]
if the input xml has indentations, it retains the indentation. there is not explicit indentation added by library
